//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodstocks.WoodstocksIMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Woodstocks.WoodstocksIMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check that the directory exists, and the file is in the directory, before retrying. If you continue to experience this error please contact the developer of this program..
        /// </summary>
        internal static string DirectoryNotFoundError {
            get {
                return ResourceManager.GetString("DirectoryNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data being imported contains more than one set of data for a toy. {0}. Please check the data file to ensure that it contains a single set of data for a toy before retrying..
        /// </summary>
        internal static string DuplicateToyMessage {
            get {
                return ResourceManager.GetString("DuplicateToyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem has been encountered whilst exporting your data. Please contact the developer of this program to correct the issue..
        /// </summary>
        internal static string ExportErrorOnCloseMessage {
            get {
                return ResourceManager.GetString("ExportErrorOnCloseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} cannot be found. Please check to ensure that the file exists before retrying. If you continue to experience this error please contact the developer of this program. .
        /// </summary>
        internal static string FileNotFoundError {
            get {
                return ResourceManager.GetString("FileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value entered for the current count is invalid. Please correct the error by entering a numerical value..
        /// </summary>
        internal static string InvalidCurrentCountMessage {
            get {
                return ResourceManager.GetString("InvalidCurrentCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoodstocksIMS has encountered a problem. If the problem continues please contact the developer of the program to resolve the issue..
        /// </summary>
        internal static string UnknownProblemMessage {
            get {
                return ResourceManager.GetString("UnknownProblemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes you have made?.
        /// </summary>
        internal static string UnsavedDataChangesMessage {
            get {
                return ResourceManager.GetString("UnsavedDataChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data was imported. If you believe data should have been imported please check that the data file is in the correct location and try again. If you continue to experience this issue contact the developer of this program..
        /// </summary>
        internal static string ZeroItemMessage {
            get {
                return ResourceManager.GetString("ZeroItemMessage", resourceCulture);
            }
        }
    }
}
